### ISSUE TITLE
compile with multiple threads

### ISSUE THREAD

**Issue by chenglin** [siboehm/lleaves#15]
I find that compile can only use one cpu core. For my model, it may take long time to compile. 

Can make compile with multiple threads, just like ` make -j ` ?

**Comment by siboehm** [comment]
This would require splitting the tree into multiple compilation units, which has some downsides and lots of additional complexity. Parallelization is also only one of the ways to improve compilation time. Therefore it's not on my roadmap currently. Most workflows that I've heard of where people use `lleaves` is to compile their final model once for deployment, hence a ~20min compile time for a very large model is a nuisance but not a show stopper.

**Comment by siboehm** [comment]
Closing, since this is not currently on my agenda.

**Comment by mirekphd** [comment]
> a ~20min compile time for a very large model is a nuisance but not a show stopper.

... which is considerably longer than it takes to train such a model (even without a GPU) on say, 1 million rows and 100 cols of data:) Not good, but I agree it is not a show-stopper given that you can parallelize compilation over multiple models.
