### ISSUE TITLE
Is it possible to pass the `num_iteration` parameter to the `predict` function?

### ISSUE THREAD

**Issue by fuyw** [siboehm/lleaves#40]
Hello Simon,

I want to ask that can we pass the `num_iteration` parameter to the predict function as in the origin LGBM API:

```
predict(data, start_iteration=0, num_iteration=None, raw_score=False, pred_leaf=False, pred_contrib=False, data_has_header=False, validate_features=False, **kwargs)
```

**Comment by siboehm** [comment]
Why did you close it? Did you not end up needing the feature after all?

**Comment by fuyw** [comment]
Hi Simon, I found that I can set the `num_iteration` parameter when I save the model instead. So I closed the issue

```
lgb.save(booster, filename, num_iteration = NULL)
```
