### ISSUE TITLE
Enabling passing unpickled model directly rather than just through the mode.txt file

### ISSUE THREAD

**Issue by faithfulalabi** [siboehm/lleaves#45]
* Hey, thanks for your great work on this. I'm currently looking to use your tool for optimizing a model in production. When the model is trained, it doesn't save to a model.txt file; instead, it's dumped as a pickle object. Would it be possible to load the unpickled model directly into the `lleaves.Model` function?

**Comment by siboehm** [comment]
Hi! That's currently not possible and I probably won't support it in the future either. It makes the implementation much simpler to load the model.txt instead of loading a pickled model :)

You could try storing the model.txt in an in-memory tmp-file, using code roughly like this:
```
import lightgbm as lgb
import tempfile

with tempfile.NamedTemporaryFile(mode='w+b', delete=False, suffix='.txt') as tmp_file:
    model.save_model(tmp_file.name)
    print(f"Model saved to: {tmp_file.name}")

loaded_model = lleaves.Model(tmp_file.name)
```

**Comment by faithfulalabi** [comment]
Thanks for the fast response and sample code. Was going to do that as a work around but thought I'd ask first. Thanks again 😄
