### ISSUE TITLE
C/C++ Api support

### ISSUE THREAD

**Issue by Bacteriaphage** [siboehm/lleaves#72]
Thanks for your amazing work! I am wondering whether we have any C/C++ API to use the compiled model. Because we are targeting faster prediction, it probably makes sense to load the compiled model and run the prediction with C/C++ instead of python, so the time intensive applications can use this smoothly.

**Comment by siboehm** [comment]
https://lleaves.readthedocs.io/en/latest/development.html#interfacing-with-a-compiled-model-in-c
